
package com.itroi.itroi.serviceimplementation;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "ClientFault", targetNamespace = "http://itroi.com/itroi/Exception")
public class ClientFaultException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ClientFaultException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ClientFaultException_Exception(String message, ClientFaultException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ClientFaultException_Exception(String message, ClientFaultException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.itroi.itroi.serviceimplementation.ClientFaultException
     */
    public ClientFaultException getFaultInfo() {
        return faultInfo;
    }

}
