
package com.itroi.itroi.serviceimpl;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "cartService", targetNamespace = "http://serviceimpl.itroi.itroi.com/")
@XmlSeeAlso({
    com.itroi.itroi.serviceimpl.ObjectFactory.class,
    com.itroi.itroi.exception.ObjectFactory.class
})
public interface CartService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @throws ClientFaultException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "addProductToCart", targetNamespace = "http://serviceimpl.itroi.itroi.com/", className = "com.itroi.itroi.serviceimpl.AddProductToCart")
    @ResponseWrapper(localName = "addProductToCartResponse", targetNamespace = "http://serviceimpl.itroi.itroi.com/", className = "com.itroi.itroi.serviceimpl.AddProductToCartResponse")
    @Action(input = "http://serviceimpl.itroi.itroi.com/cartService/addProductToCartRequest", output = "http://serviceimpl.itroi.itroi.com/cartService/addProductToCartResponse", fault = {
        @FaultAction(className = ClientFaultException_Exception.class, value = "http://serviceimpl.itroi.itroi.com/cartService/addProductToCart/Fault/ClientFaultException")
    })
    public void addProductToCart(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1)
        throws ClientFaultException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.itroi.itroi.serviceimpl.Cart>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllCarts", targetNamespace = "http://serviceimpl.itroi.itroi.com/", className = "com.itroi.itroi.serviceimpl.GetAllCarts")
    @ResponseWrapper(localName = "getAllCartsResponse", targetNamespace = "http://serviceimpl.itroi.itroi.com/", className = "com.itroi.itroi.serviceimpl.GetAllCartsResponse")
    @Action(input = "http://serviceimpl.itroi.itroi.com/cartService/getAllCartsRequest", output = "http://serviceimpl.itroi.itroi.com/cartService/getAllCartsResponse")
    public List<Cart> getAllCarts();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.itroi.itroi.serviceimpl.Cart
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCartById", targetNamespace = "http://serviceimpl.itroi.itroi.com/", className = "com.itroi.itroi.serviceimpl.GetCartById")
    @ResponseWrapper(localName = "getCartByIdResponse", targetNamespace = "http://serviceimpl.itroi.itroi.com/", className = "com.itroi.itroi.serviceimpl.GetCartByIdResponse")
    @Action(input = "http://serviceimpl.itroi.itroi.com/cartService/getCartByIdRequest", output = "http://serviceimpl.itroi.itroi.com/cartService/getCartByIdResponse")
    public Cart getCartById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.itroi.itroi.serviceimpl.Cart
     * @throws ClientFaultException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCart", targetNamespace = "http://serviceimpl.itroi.itroi.com/", className = "com.itroi.itroi.serviceimpl.GetCart")
    @ResponseWrapper(localName = "getCartResponse", targetNamespace = "http://serviceimpl.itroi.itroi.com/", className = "com.itroi.itroi.serviceimpl.GetCartResponse")
    @Action(input = "http://serviceimpl.itroi.itroi.com/cartService/getCartRequest", output = "http://serviceimpl.itroi.itroi.com/cartService/getCartResponse", fault = {
        @FaultAction(className = ClientFaultException_Exception.class, value = "http://serviceimpl.itroi.itroi.com/cartService/getCart/Fault/ClientFaultException")
    })
    public Cart getCart(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws ClientFaultException_Exception
    ;

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addCart", targetNamespace = "http://serviceimpl.itroi.itroi.com/", className = "com.itroi.itroi.serviceimpl.AddCart")
    @ResponseWrapper(localName = "addCartResponse", targetNamespace = "http://serviceimpl.itroi.itroi.com/", className = "com.itroi.itroi.serviceimpl.AddCartResponse")
    @Action(input = "http://serviceimpl.itroi.itroi.com/cartService/addCartRequest", output = "http://serviceimpl.itroi.itroi.com/cartService/addCartResponse")
    public void addCart(
        @WebParam(name = "arg0", targetNamespace = "")
        Cart arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.itroi.itroi.serviceimpl.Cart
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkout", targetNamespace = "http://serviceimpl.itroi.itroi.com/", className = "com.itroi.itroi.serviceimpl.Checkout")
    @ResponseWrapper(localName = "checkoutResponse", targetNamespace = "http://serviceimpl.itroi.itroi.com/", className = "com.itroi.itroi.serviceimpl.CheckoutResponse")
    @Action(input = "http://serviceimpl.itroi.itroi.com/cartService/checkoutRequest", output = "http://serviceimpl.itroi.itroi.com/cartService/checkoutResponse")
    public Cart checkout(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws ClientFaultException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "removeProductFromCart", targetNamespace = "http://serviceimpl.itroi.itroi.com/", className = "com.itroi.itroi.serviceimpl.RemoveProductFromCart")
    @ResponseWrapper(localName = "removeProductFromCartResponse", targetNamespace = "http://serviceimpl.itroi.itroi.com/", className = "com.itroi.itroi.serviceimpl.RemoveProductFromCartResponse")
    @Action(input = "http://serviceimpl.itroi.itroi.com/cartService/removeProductFromCartRequest", output = "http://serviceimpl.itroi.itroi.com/cartService/removeProductFromCartResponse", fault = {
        @FaultAction(className = ClientFaultException_Exception.class, value = "http://serviceimpl.itroi.itroi.com/cartService/removeProductFromCart/Fault/ClientFaultException")
    })
    public void removeProductFromCart(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1)
        throws ClientFaultException_Exception
    ;

}
