
package com.itroi.itroi.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "cartImplementationService", targetNamespace = "http://serviceimpl.itroi.itroi.com/", wsdlLocation = "http://localhost:8081/ws/carts?wsdl")
public class CartImplementationService
    extends Service
{

    private final static URL CARTIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException CARTIMPLEMENTATIONSERVICE_EXCEPTION;
    private final static QName CARTIMPLEMENTATIONSERVICE_QNAME = new QName("http://serviceimpl.itroi.itroi.com/", "cartImplementationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/ws/carts?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CARTIMPLEMENTATIONSERVICE_WSDL_LOCATION = url;
        CARTIMPLEMENTATIONSERVICE_EXCEPTION = e;
    }

    public CartImplementationService() {
        super(__getWsdlLocation(), CARTIMPLEMENTATIONSERVICE_QNAME);
    }

    public CartImplementationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CARTIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public CartImplementationService(URL wsdlLocation) {
        super(wsdlLocation, CARTIMPLEMENTATIONSERVICE_QNAME);
    }

    public CartImplementationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CARTIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public CartImplementationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CartImplementationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CartService
     */
    @WebEndpoint(name = "cartImplementationPort")
    public CartService getCartImplementationPort() {
        return super.getPort(new QName("http://serviceimpl.itroi.itroi.com/", "cartImplementationPort"), CartService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CartService
     */
    @WebEndpoint(name = "cartImplementationPort")
    public CartService getCartImplementationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.itroi.itroi.com/", "cartImplementationPort"), CartService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CARTIMPLEMENTATIONSERVICE_EXCEPTION!= null) {
            throw CARTIMPLEMENTATIONSERVICE_EXCEPTION;
        }
        return CARTIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    }

}
