
package com.itroi.itroi.serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "productImplementationService", targetNamespace = "http://serviceimpl.itroi.itroi.com/", wsdlLocation = "http://localhost:8081/ws/products?wsdl")
public class ProductImplementationService
    extends Service
{

    private final static URL PRODUCTIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRODUCTIMPLEMENTATIONSERVICE_EXCEPTION;
    private final static QName PRODUCTIMPLEMENTATIONSERVICE_QNAME = new QName("http://serviceimpl.itroi.itroi.com/", "productImplementationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/ws/products?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUCTIMPLEMENTATIONSERVICE_WSDL_LOCATION = url;
        PRODUCTIMPLEMENTATIONSERVICE_EXCEPTION = e;
    }

    public ProductImplementationService() {
        super(__getWsdlLocation(), PRODUCTIMPLEMENTATIONSERVICE_QNAME);
    }

    public ProductImplementationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUCTIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public ProductImplementationService(URL wsdlLocation) {
        super(wsdlLocation, PRODUCTIMPLEMENTATIONSERVICE_QNAME);
    }

    public ProductImplementationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUCTIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public ProductImplementationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductImplementationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProductService
     */
    @WebEndpoint(name = "productImplementationPort")
    public ProductService getProductImplementationPort() {
        return super.getPort(new QName("http://serviceimpl.itroi.itroi.com/", "productImplementationPort"), ProductService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductService
     */
    @WebEndpoint(name = "productImplementationPort")
    public ProductService getProductImplementationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceimpl.itroi.itroi.com/", "productImplementationPort"), ProductService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCTIMPLEMENTATIONSERVICE_EXCEPTION!= null) {
            throw PRODUCTIMPLEMENTATIONSERVICE_EXCEPTION;
        }
        return PRODUCTIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    }

}
