
package com.itroi.itroi.serviceimpl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "userService", targetNamespace = "http://serviceimpl.itroi.itroi.com/")
@XmlSeeAlso({
    com.itroi.itroi.exception.ObjectFactory.class,
    com.itroi.itroi.serviceimpl.ObjectFactory.class
})
public interface UserService {


    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generateUniqueUserId", targetNamespace = "http://serviceimpl.itroi.itroi.com/", className = "com.itroi.itroi.serviceimpl.GenerateUniqueUserId")
    @ResponseWrapper(localName = "generateUniqueUserIdResponse", targetNamespace = "http://serviceimpl.itroi.itroi.com/", className = "com.itroi.itroi.serviceimpl.GenerateUniqueUserIdResponse")
    @Action(input = "http://serviceimpl.itroi.itroi.com/userService/generateUniqueUserIdRequest", output = "http://serviceimpl.itroi.itroi.com/userService/generateUniqueUserIdResponse")
    public int generateUniqueUserId();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.itroi.itroi.serviceimpl.User
     * @throws ClientFaultException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserforAuth", targetNamespace = "http://serviceimpl.itroi.itroi.com/", className = "com.itroi.itroi.serviceimpl.GetUserforAuth")
    @ResponseWrapper(localName = "getUserforAuthResponse", targetNamespace = "http://serviceimpl.itroi.itroi.com/", className = "com.itroi.itroi.serviceimpl.GetUserforAuthResponse")
    @Action(input = "http://serviceimpl.itroi.itroi.com/userService/getUserforAuthRequest", output = "http://serviceimpl.itroi.itroi.com/userService/getUserforAuthResponse", fault = {
        @FaultAction(className = ClientFaultException_Exception.class, value = "http://serviceimpl.itroi.itroi.com/userService/getUserforAuth/Fault/ClientFaultException")
    })
    public User getUserforAuth(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws ClientFaultException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.itroi.itroi.serviceimpl.User
     * @throws ClientFaultException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserById", targetNamespace = "http://serviceimpl.itroi.itroi.com/", className = "com.itroi.itroi.serviceimpl.GetUserById")
    @ResponseWrapper(localName = "getUserByIdResponse", targetNamespace = "http://serviceimpl.itroi.itroi.com/", className = "com.itroi.itroi.serviceimpl.GetUserByIdResponse")
    @Action(input = "http://serviceimpl.itroi.itroi.com/userService/getUserByIdRequest", output = "http://serviceimpl.itroi.itroi.com/userService/getUserByIdResponse", fault = {
        @FaultAction(className = ClientFaultException_Exception.class, value = "http://serviceimpl.itroi.itroi.com/userService/getUserById/Fault/ClientFaultException")
    })
    public User getUserById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws ClientFaultException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws ClientFaultException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createUser", targetNamespace = "http://serviceimpl.itroi.itroi.com/", className = "com.itroi.itroi.serviceimpl.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://serviceimpl.itroi.itroi.com/", className = "com.itroi.itroi.serviceimpl.CreateUserResponse")
    @Action(input = "http://serviceimpl.itroi.itroi.com/userService/createUserRequest", output = "http://serviceimpl.itroi.itroi.com/userService/createUserResponse", fault = {
        @FaultAction(className = ClientFaultException_Exception.class, value = "http://serviceimpl.itroi.itroi.com/userService/createUser/Fault/ClientFaultException")
    })
    public void createUser(
        @WebParam(name = "arg0", targetNamespace = "")
        User arg0)
        throws ClientFaultException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws ClientFaultException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "deleteUser", targetNamespace = "http://serviceimpl.itroi.itroi.com/", className = "com.itroi.itroi.serviceimpl.DeleteUser")
    @ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "http://serviceimpl.itroi.itroi.com/", className = "com.itroi.itroi.serviceimpl.DeleteUserResponse")
    @Action(input = "http://serviceimpl.itroi.itroi.com/userService/deleteUserRequest", output = "http://serviceimpl.itroi.itroi.com/userService/deleteUserResponse", fault = {
        @FaultAction(className = ClientFaultException_Exception.class, value = "http://serviceimpl.itroi.itroi.com/userService/deleteUser/Fault/ClientFaultException")
    })
    public void deleteUser(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws ClientFaultException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws ClientFaultException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://serviceimpl.itroi.itroi.com/", className = "com.itroi.itroi.serviceimpl.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://serviceimpl.itroi.itroi.com/", className = "com.itroi.itroi.serviceimpl.UpdateUserResponse")
    @Action(input = "http://serviceimpl.itroi.itroi.com/userService/updateUserRequest", output = "http://serviceimpl.itroi.itroi.com/userService/updateUserResponse", fault = {
        @FaultAction(className = ClientFaultException_Exception.class, value = "http://serviceimpl.itroi.itroi.com/userService/updateUser/Fault/ClientFaultException")
    })
    public void updateUser(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        User arg1)
        throws ClientFaultException_Exception
    ;

}
